### ISSUE TITLE
use WigSound for adaptive_sound

### ISSUE THREAD

**Issue by P1tt187** [DigglesMods/WigSound#1]
in der Datei `Wiggles\Data\Scripts\init\adaptiveinit.tcl` befinden sich die initialisierungen für die Musik
aktuell sieht es noch so aus, als würden die aufrufe die WigHelper.exe ansprechen
Die WigHelper funktioniert beispielsweise nicht auf linux systemen
Wenn ich es richtig verstehe müsste man einen ähnlichen patch wie für den normalen sound entwickeln um alle aufrufe von adaptive_sound zu ersetzen

**Comment by cech12** [comment]
In der angesprochenen Datei werden meines Erachtens nur den MP3-Dateien andere Namen gegeben bzw. einem Namen mehrere MP3-Dateien zugewiesen. 
In anderen Dateien gibt es dann die Aufrufe , die das "Theme" ändern und somit eine der Dateien, die diesem Theme zugewiesen ist, abspielt.

Leider kann man diese _adaptive_sound_ Methode nirgends einsehen. Ich denke mal, dass sie in einer der exe-Dateien ist.

Es gibt leider sehr viele Stellen in den tcl-Dateien, die man für solch einen Patch anfassen müsste. Aber es passiert ja noch mehr als nur die die Dateien einem Theme zuordnen und das Theme zu wechseln. Zum Beispiel wird vom Spiel entschieden, welcher Modus des Themes gerade abgespielt werden soll. Also wann ein Kampf beginnt und endet. Da kommt man wahrscheinlich nicht ran. :/

Somit ist das Auslagern dieser _adaptive_sound_ Methode vermutlich nicht machbar :/ Aber ich lasse mich gern eines Besseren belehren :D
